"""Human-readable labels for PhiUSIIL features used in plain-English explanations."""

FEATURE_DISPLAY_NAMES: dict[str, str] = {
    "URLLength": "URL length",
    "DomainLength": "domain length",
    "IsDomainIP": "domain being an IP address",
    "URLSimilarityIndex": "URL-domain similarity",
    "CharContinuationRate": "character continuation rate",
    "TLDLegitimateProb": "TLD legitimacy probability",
    "URLCharProb": "URL character probability",
    "TLDLength": "TLD length",
    "NoOfSubDomain": "number of subdomains",
    "HasObfuscation": "URL obfuscation",
    "NoOfObfuscatedChar": "obfuscated character count",
    "ObfuscationRatio": "obfuscation ratio",
    "NoOfLettersInURL": "letter count in URL",
    "LetterRatioInURL": "letter ratio in URL",
    "NoOfDegitsInURL": "digit count in URL",
    "DegitRatioInURL": "digit ratio in URL",
    "NoOfEqualsInURL": "equals sign count",
    "NoOfQMarkInURL": "question mark count",
    "NoOfAmpersandInURL": "ampersand count",
    "NoOfOtherSpecialCharsInURL": "special character count",
    "SpacialCharRatioInURL": "special character ratio",
    "IsHTTPS": "HTTPS usage",
    "LineOfCode": "HTML line count",
    "LargestLineLength": "largest HTML line length",
    "HasTitle": "page title presence",
    "DomainTitleMatchScore": "domain-title match score",
    "URLTitleMatchScore": "URL-title match score",
    "HasFavicon": "favicon presence",
    "Robots": "robots.txt presence",
    "IsResponsive": "responsive design",
    "NoOfURLRedirect": "URL redirect count",
    "NoOfSelfRedirect": "self-redirect count",
    "HasDescription": "meta description presence",
    "NoOfPopup": "popup count",
    "NoOfiFrame": "iframe count",
    "HasExternalFormSubmit": "external form submission",
    "HasSocialNet": "social network links",
    "HasSubmitButton": "submit button presence",
    "HasHiddenFields": "hidden form fields",
    "HasPasswordField": "password field presence",
    "Bank": "banking-related content",
    "Pay": "payment-related content",
    "Crypto": "cryptocurrency-related content",
    "HasCopyrightInfo": "copyright information",
    "NoOfImage": "image count",
    "NoOfCSS": "CSS file count",
    "NoOfJS": "JavaScript file count",
    "NoOfSelfRef": "self-referencing link count",
    "NoOfEmptyRef": "empty reference count",
    "NoOfExternalRef": "external reference count",
}
